# GitHub Sponsors funding links for PrimeBible WordPress Plugin
# 501(c)(3) Nonprofit - All donations support free Bible study tools

# Custom donation link to PrimeBible.com
custom: ["https://primebible.com/donate", "https://primebible.com/support"]
